[package]
name = "pxollyrs"
version = "0.2.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.3", features = ["json"] }
config = { version = "0.11", features = ["toml"] }
tokio = { version = "1.5.0", features = ["full"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64" }
log = { version = "0.4.14" }
simple_logger = "1.13.0"
axum = "0.2.7"
thiserror = "1.0.29"
