[package]
name = "pxollyrs"
version = "0.1.0"
edition = "2018"

[dependencies]
# web http
actix-web = { version = "4.0.0-beta.6" }

# client http
reqwest = { version = "0.11.3", features = ["json"] }

# config file
config = { version = "0.11", features = ["toml"] }

# tokio async
tokio = { version = "1.5.0", features = ["full"] }

# serde and base types
serde = { version = "1.0.126", features = ["derive"] }
serde_json = { version = "1.0.64" }

# log
env_logger = { version = "0.8" }
log = { version = "0.4.14" }

# result
anyhow = "1.0.42"
derive_more = "0.99.16"
