[pxolly]
# str: - токен от @pxolly
token = "v8x.Cym..."

[vk]
# strdecimal: - версия API, крайне не рекомендуется менять версию
version = "5.131"
# str: - токен от Вконтакте
token = "vk1.a.DU..."

[application]
# bool: - автопривязка сервера к @pxolly 
is_bind = false
# port(int16): порт сервера (обязательный)
# ip(ipvaddr): IP сервера (опциональный, default = 127.0.0.1)
# host(str): хост сервера (опциональный, e.g https://ngrok.http)
server = { port = 1488 }
# level(str): - уровень лога (опциональный, default = info)
logger = { level = "info" }

# ВНИМАНИЕ! Параметр is_bind означает, что вебхук будет пытаться привязывать свой сервер с @pxolly.
# Вебхук отправляет запрос на @pxolly с host;
# то есть вебхук работает через IP, а host должен указывать как-то на IP;
# если host отсутствует, то вебхук может пытаться взять публичные айпи, чтобы получить хост;
# однако, если попытка провалилась, то вебхук отправит вам ошибки;
# и чтобы решить эту проблему, нужно взять туннели, такие как ngrok, и т.д.