[pxolly]
token = "v8x.Cym..."

[vk]
version = "5.131"
token = "vk1.a.DU..."

[application]
is_bind = false
server = { port = 1488, host = " https://34a2-94-245-163-148.jp.ngrok.io" }
database = { path = "chat.json" }
logger = { level = "info" } 