[pxolly]
secret_key = "secret_key"
token = "v8x.CymULq...."

[vk]
version = "5.131"
token = "vk1.a.NJ52iO-4S..."

[application]
is_bind = true
server = { ip = "localhost", port = 1488, host = "https://myhost.com" }
database = { path = "config/chat.json" }
logger = { level = "info" }