name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Cargo build
      run: cargo build --verbose
    
    - name: Cargo clippy
      run: cargo clippy --verbose
      
    - name: Run fmt
      run: cargo fmt --verbose
    
    - name: Run tests
      run: cargo test --verbose
